package com.example.demo.mock;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

import com.example.demo.post.domain.Post;
import com.example.demo.post.service.port.PostRepository;

public class FakePostRepository implements PostRepository {

	private final List<Post> data = new ArrayList<>();
	private Long autoGeneratedId = 0L;

	@Override
	public Optional<Post> findById(long id) {
		return data.stream().filter(item -> item.getId().equals(id)).findAny();
	}

	@Override
	public Post save(Post post) {
		if (post.getId() == null || post.getId() == 0) {

			Post newPost = Post.builder()
				.id(autoGeneratedId++)
				.content(post.getContent())
				.createdAt(post.getCreatedAt())
				.modifiedAt(post.getModifiedAt())
				.writer(post.getWriter())
				.build();
			data.add(newPost);
			return newPost;
		} else {
			data.removeIf(i -> Objects.equals(i.getId(), post.getId()));
			data.add(post);
			return post;
		}
	}
}
